"""Constants for Electricity Pro."""

from homeassistant.const import Platform

DOMAIN = "electricity_pro"

CONF_SETUP_METHOD = "setup_method"
CONF_SOURCE_PROFILE = "source_profile"
CONF_TIBBER_DEVICE = "tibber_device"
CONF_POWER_ENTITY = "power_entity"
CONF_PRICE_ENTITY = "price_entity"
CONF_ENERGY_ENTITY = "energy_entity"
CONF_ACCUMULATED_COST_TODAY_ENTITY = "accumulated_cost_today_entity"
CONF_PEAK_POWER_TODAY_ENTITY = "peak_power_today_entity"
CONF_CURRENT_L1_ENTITY = "current_l1_entity"
CONF_CURRENT_L2_ENTITY = "current_l2_entity"
CONF_CURRENT_L3_ENTITY = "current_l3_entity"
CONF_VOLTAGE_L1_ENTITY = "voltage_l1_entity"
CONF_VOLTAGE_L2_ENTITY = "voltage_l2_entity"
CONF_VOLTAGE_L3_ENTITY = "voltage_l3_entity"
CONF_MONTHLY_PEAK_HOUR_CONSUMPTION_ENTITY = "monthly_peak_hour_consumption_entity"
CONF_MONTHLY_PEAK_HOUR_TIME_ENTITY = "monthly_peak_hour_time_entity"
CONF_GRID_FEE_PER_KWH = "grid_fee_per_kwh"
CONF_GRID_FEE_HIGH_PER_KWH = "grid_fee_high_per_kwh"
CONF_GRID_FEE_HIGH_START = "grid_fee_high_start"
CONF_GRID_FEE_HIGH_END = "grid_fee_high_end"
CONF_GRID_FEE_HIGH_SEASON_START = "grid_fee_high_season_start"
CONF_GRID_FEE_HIGH_SEASON_END = "grid_fee_high_season_end"
CONF_GRID_FEE_WORKDAY_ENTITY = "grid_fee_workday_entity"
CONF_FIXED_SUPPLIER_FEE_MONTHLY = "fixed_supplier_fee_monthly"
CONF_FIXED_GRID_FEE_MONTHLY = "fixed_grid_fee_monthly"
CONF_GOOD_PRICE_THRESHOLD = "good_price_threshold"
CONF_FORECAST_PRICE_AREA = "forecast_price_area"
CONF_FORECAST_CURRENCY = "forecast_currency"
CONF_FORECAST_NORDPOOL_CONFIG_ENTRY = "forecast_nordpool_config_entry"
CONF_PRICING_STRATEGY = "pricing_strategy"
CONF_PRICE_INCLUDED_COMPONENTS = "price_included_components"
CONF_PRICE_VAT_TREATMENT = "price_vat_treatment"
CONF_PRICE_COMPLETENESS = "price_completeness"

PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.BINARY_SENSOR]
